services:
  postgres:
    container_name: "postgres_whc_${container_postfix}"
    image: postgres:latest
    environment:
      - POSTGRES_USER=whuser
      - POSTGRES_PASSWORD=whuserpassword
      - POSTGRES_DB=wh
    ports:
      - "5432:5432"
    networks: [ 'whnet' ]
  wh:
    environment:
      wh.datasource.local-url: "jdbc:postgresql://postgres:5432/wh"
    container_name: "backfront_whc_${container_postfix}"
    image: "alexeyrosolko/whc:1.${docker_image_version}"
    ports:
      - "8085:8080"
    depends_on:
      - postgres
    networks: [ 'whnet' ]
networks: { whnet: { } }